export const abi = [
    {
        type: "constructor",
        inputs: [
            { type: "address", name: "vrfCoordinatorV2" },
            { type: "uint64", name: "subscriptionId" },
            { type: "uint256", name: "entranceFee" },
            { type: "bytes32", name: "gasLane" },
            { type: "uint32", name: "callbackGasLimit" },
            { type: "uint256", name: "interval" },
        ],
    },
    {
        type: "event",
        anonymous: false,
        name: "RaffleEnter",
        inputs: [{ type: "address", name: "player", indexed: true }],
    },
    {
        type: "event",
        anonymous: false,
        name: "RequestedRaffleWinner",
        inputs: [{ type: "uint256", name: "requestId", indexed: true }],
    },
    {
        type: "event",
        anonymous: false,
        name: "WinnerPicked",
        inputs: [{ type: "address", name: "indexedwinner", indexed: false }],
    },
    {
        type: "function",
        name: "checkUpkeep",
        stateMutability: "view",
        inputs: [{ type: "bytes" }],
        outputs: [{ type: "bool", name: "upkeepNeeded" }, { type: "bytes" }],
    },
    {
        type: "function",
        name: "enterRaffle",
        stateMutability: "payable",
        inputs: [],
        outputs: [],
    },
    {
        type: "function",
        name: "getEntranceFee",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "getInterval",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "getLastTimeStamp",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "getNumOfPlayers",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "getNumWords",
        stateMutability: "pure",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "getPlayer",
        stateMutability: "view",
        inputs: [{ type: "uint256", name: "index" }],
        outputs: [{ type: "address" }],
    },
    {
        type: "function",
        name: "getRaffleState",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint8" }],
    },
    {
        type: "function",
        name: "getRecentWinner",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "address" }],
    },
    {
        type: "function",
        name: "getRequestConfirmations",
        stateMutability: "pure",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "getSubscriptionId",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint64" }],
    },
    {
        type: "function",
        name: "performUpkeep",
        inputs: [{ type: "bytes" }],
        outputs: [],
    },
    {
        type: "function",
        name: "rawFulfillRandomWords",
        inputs: [
            { type: "uint256", name: "requestId" },
            { type: "uint256[]", name: "randomWords" },
        ],
        outputs: [],
    },
] as const;
